"""
Django settings for sql_ai_project project.

Generated by 'django-admin startproject' using Django 4.2.21.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env at project root (if present)
load_dotenv(BASE_DIR / '.env')

# ---- Security & env-driven config ----
# IMPORTANT: never keep a real secret here. Read from env with a safe default for dev.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-=aazks+w_@ux%#at-dads!__o5(ku(8@qlgh(x3u6-sd-a)%w3')

DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() == 'true'

# Accept hosts from env. In prod, set DJANGO_ALLOWED_HOSTS="app.example.com"
ALLOWED_HOSTS = (
    os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',')
    if os.environ.get('DJANGO_ALLOWED_HOSTS')
    else ['localhost', '127.0.0.1', '0.0.0.0']
)

# Needed for POST forms/cookies when served behind Cloudflare
# e.g. DJANGO_CSRF_ORIGIN="https://app.example.com"
CSRF_TRUSTED_ORIGINS = (
    [os.environ['DJANGO_CSRF_ORIGIN']]
    if os.environ.get('DJANGO_CSRF_ORIGIN')
    else []
)

# Trust the Cloudflare/ingress proxy for HTTPS
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# (Keep SECURE_SSL_REDIRECT off unless you confirm cloudflared sets X-Forwarded-Proto=https.)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'chat_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise must be early to serve static files in the container
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sql_ai_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'chat_app' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sql_ai_project.wsgi.application'


# ---- Database (SQLite for now, path can come from env for persistence) ----
SQLITE_PATH = os.environ.get('SQLITE_PATH')  # e.g. "/data/db.sqlite3" set in .env
# --- Database: Postgres via env; fallback to SQLite for dev ---
DB_NAME = os.environ.get("POSTGRES_DB")
DB_USER = os.environ.get("POSTGRES_USER")
DB_PASSWORD = os.environ.get("POSTGRES_PASSWORD")
DB_HOST = os.environ.get("POSTGRES_HOST") or os.environ.get("DB_HOST")  # allow either
DB_PORT = os.environ.get("POSTGRES_PORT", "5432")

if all([DB_NAME, DB_USER, DB_PASSWORD, DB_HOST]):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": DB_NAME,
            "USER": DB_USER,
            "PASSWORD": DB_PASSWORD,
            "HOST": DB_HOST,
            "PORT": DB_PORT,
            "CONN_MAX_AGE": 60,  # keep-alive for perf
            "OPTIONS": {"sslmode": os.environ.get("POSTGRES_SSLMODE", "disable")},
        }
    }
else:
    # Fallback (works in dev or before DB is configured)
    SQLITE_PATH = os.environ.get("SQLITE_PATH")
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": SQLITE_PATH if SQLITE_PATH else BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'